apiVersion: v1
kind: Service
metadata:
  name: sentiment-analyse-web-app
spec:
  type: LoadBalancer
  selector:
    app: sentiment-analyse-web-app
  ports:
    - protocol: TCP
      port: 80              # The port that the service will expose externally
      targetPort: 5000      # The port on which the Flask app is running inside the container