name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.12'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8
#       - name: Run linter
#         run: flake8 .

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
            version: 'v1.30.2' # default is latest stable
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1



      - name: Build, tag and push docker image to ECR
        env:
            REGISTRY: ${{ vars.REGISTRY }}
            REPOSITORY: sentiment-analyse-web-app
            IMAGE_TAG: latest
        run: |
          echo $REGISTRY
          echo $REPOSITORY
          echo $IMAGE_TAG
          docker build -t $REPOSITORY .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks --region ap-south-1 update-kubeconfig --name sentiment-analysis-app
      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl set image deployment/sentiment-analyse-web-app sentiment-analyse-web-app=686754180139.dkr.ecr.ap-south-1.amazonaws.com/sentiment-analyse-web-app:latest --record